exports('AddCustomApp', function(...) end)
exports('RemoveCustomApp', function(...) end)

AddEventHandler('onClientResourceStop', function(...) end)
AddEventHandler('onResourceStop', function(...) end)
RegisterNUICallback('CustomApp', function(data, cb) end)
RegisterNUICallback('PopUp', function(data, cb) end)
RegisterNUICallback('SetPopUp', function(data, cb) end)
exports('SetPopUp', function(...) end)
RegisterNUICallback('ContextMenu', function(data, cb) end)
RegisterNUICallback('SetContextMenu', function(data, cb) end)
exports('SetContextMenu', function(...) end)
RegisterNUICallback('UsedComponent', function(data, cb) end)
RegisterNUICallback('ShowComponent', function(data, cb) end)
exports('ShowComponent', function(...) end)